# NumPyメモ
参考：https://deepage.net/features/numpy/  
参考：Udemy「米国データサイエンティストがやさしく教えるデータサイエンスのためのPythonの講座」

In [2]:
import numpy as np

In [5]:
# numpyのモジュールの場所を表示
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Arrays(ndarray)
N次元配列(ndarray)を作成するメソッド  
ndarrayの特徴は以下。  
* 同じ型を持つ要素しか格納することができない
* 各次元ごとの(2次元なら列ごとや行ごと)の要素数は必ず一定
* C言語を元に、最適化された行列演算を行うため効率的な処理をすることができる


In [8]:
# 3次元ベクトルが一つのイメージ
np.array([1, 2, 3])

array([1, 2, 3])

In [12]:
# ３×３の行列を定義
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
# numpy.arrayの要素はnumpy独自のデータタイプであることに注意
print(type(matrix[0][0]))

# 普通の1の場合
print(type(1))

<class 'numpy.int64'>
<class 'int'>


ndarrayのデータ型としては下記をよく使う  
・uint8: 0-255（８ビット）の整数  
・float32または64: 32,64ビットの小数点型。機械学習に使うデータを保存するときに使う　　

In [21]:
# 使用例
ndarray = np.array([1, 2, 3], dtype=np.float32)
ndarray

array([1., 2., 3.], dtype=float32)

In [4]:
# 行数が足りなくても補完して演算を行う(broadcasting)
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array1 + array2)

print(array2 + 4)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]



ndarray.shapeで（行、列）が分かる

In [79]:
array2.shape

(3, 3)

In [81]:
array3 = np.array([[1, 2], [4, 5], [7, 8]])
array3

array([[1, 2],
       [4, 5],
       [7, 8]])

In [82]:
# tupleの形（行、列）で返ってくる
array3.shape

(3, 2)

In [25]:
array3.reshape(2, 3)

array([[1, 2, 4],
       [5, 7, 8]])

## Numpy arrayの演算
リストと違い、要素ごとに演算子が適用される。

In [3]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.zeros((3, 3))
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [123]:
array2[0]

array([0., 0., 0.])

In [125]:
# 行に単一の数を代入すると行の各要素に適用される。
array2[0] = 1
array2

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 行にリストを代入すると、そのまま各要素に代入される。
array2[0] = [1, 2, 3]
array2

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# スライシングを利用して０行目と１行目に代入する。
array2[:2] = [1, 2, 3]
array2

array([[1., 2., 3.],
       [1., 2., 3.],
       [0., 0., 0.]])

In [4]:
# 行列同士の加法
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
array2

array([[1., 2., 3.],
       [1., 2., 3.],
       [0., 0., 0.]])

In [8]:
array1 + array2

array([[2., 4., 6.],
       [5., 7., 9.],
       [7., 8., 9.]])

対応するインデックス同士で足し算が行われる。
掛け算も同様。

In [9]:
array1 * array2

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.],
       [ 0.,  0.,  0.]])

## 次元について

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3]])
print(array1)
# array1の書き方だと、単に3つの要素の1次元配列になる(ベクトル)
print(array1.shape)
print(array1.ndim)

print()

# array2の書き方だと、1行しかない2次元配列の扱い（行列）
print(array2)
print(array2.ndim)
print(array2.shape)

[1 2 3]
(3,)
1

[[1 2 3]]
2
(1, 3)


基本的にnp.array()内の初めと終わりの[]の数が次元数に対応すると考えてOK.  
例）np.array([[1, 2, 3]]) →2次元

In [11]:
# ndarrayの次元を列方向（横）に増やす。axisにはshapeのタプルのインデックスを指定するイメージ。指定したインデックスの前のインデックスに1が追加される。
array1_expand = np.expand_dims(array1, axis=0)
print(array1_expand.shape)
print(array1_expand)

print()
# ndarrayの次元を行方向（縦）に増やす
array2_expand = np.expand_dims(array2, axis=1)
print(array2_expand.shape)
print(array2_expand)



(1, 3)
[[1 2 3]]

(1, 1, 3)
[[[1 2 3]]]


In [86]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# 奥行2（行列数2）、縦3、横3の3次元配列
a3 = np.array([a1, a2])


print(a3)
print('次元数：{}'.format(a3.ndim))
print('シェイプ：{}'.format(a3.shape))
# 2つ目の行列の特定の場所から値を取り出す。
print(a3[1][2][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
次元数：3
シェイプ：(2, 3, 3)
80


## 行列のスライシング
普通のリストと同じ要領でスライシングできる。


In [4]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [5]:
ndarray[0, 2]

3

In [41]:
ndarray[:2, :2]

array([[1, 2],
       [5, 6]])

In [43]:
ndarray[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [88]:
# 3次元配列のスライシング
# 3次元配列
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# 奥行2、縦3、横3
a3 = np.array([a1, a2])

print(a3)
print('次元数：{}'.format(a3.ndim))
print('シェイプ：{}'.format(a3.shape))
# 下記の場合、行列数、行ではスライシングされずインデックス2の列でa1,a2をまたいでスライシングされる。
a3[:, : ,2]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
次元数：3
シェイプ：(2, 3, 3)


array([[ 3,  6,  9],
       [30, 60, 90]])

In [87]:
# 下記のようなスライシングは左から順に実行され、[:]は何もスライシングしないことを意味する。
a3[1][:][2]
# こんな書き方もできる。
# a3[:][:][:][:][:][:][:][:][:][:][1]

array([70, 80, 90])

## 1DArrayの生成
np.arange(), np.linspce(),np.logspace()で1DArrayを作成することができる。

In [55]:
# arange(始点、終点、公差)　→使い方はrange()関数と同じ
np.arange(1, 10, 2)


array([1, 3, 5, 7, 9])

In [58]:
# np.linspace（始点、終点、要素数） *lin = linearのこと
# (終点-始点)/(要素数 -1)が公差となる。
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [58]:
# endpoint=Falseをつけることで終点の値は含まなくする。
# この場合、公差は(終点-始点)/要素数
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [62]:
# 10を底として、（始点0、終点3、要素数10）、10 ** (3/9)が公差の配列を生成
np.logspace(0, 3, 10)


array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

## 行列の生成
* np.zeros: 零行列を生成  
* np.ones: 要素がすべて1の行列を生成  
* np.eye: 単位行列を生成。正方行列以外も生成可能。


In [9]:
# tupleでshapeを与える
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
shape = (3)
np.zeros(shape)

array([0., 0., 0.])

In [12]:
shape = (2, 3)
np.ones(shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# 基本は正方行列なので、行数だけ指定すればOK
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
# 連番の行列を作りたいときは下記のようにすると楽
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 疑似乱数生成
np.randomを使うことで、疑似乱数（真の意味でランダムではない）を生成できる。  
データサイエンスの分野では疑似乱数で十分。  
成果物の再現性を担保する意味で、基本的には生成する際はseedを指定して乱数を生成するのがよい。  

In [14]:
np.random.rand(5, 4)

array([[0.40803534, 0.79150166, 0.10847023, 0.88600852],
       [0.68038992, 0.76597534, 0.60811967, 0.44666127],
       [0.16487394, 0.70590536, 0.34010716, 0.40918669],
       [0.63003548, 0.04862081, 0.31428605, 0.91258847],
       [0.48420165, 0.55842859, 0.43897334, 0.83971779]])

In [21]:
# random.seedは引数の値が固定なら同じ乱数を返す。（ただし、同じセル内のみ）
np.random.seed(2)
np.random.rand(3, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])

In [26]:
# 標準正規分布(standrd normal distribution、平均0、分散1の正規分布)からランダムに行列を生成する(よく使われれる)
np.random.randn(3, 4)

array([[-0.67767558, -1.43943903,  0.52429643,  0.73527958],
       [-0.65325027,  0.84245628, -0.38151648,  0.06648901],
       [-1.09873895,  1.58448706, -2.65944946, -0.09145262]])

In [27]:
# randomな整数で行列を生成(下記は10から100までの整数)
np.random.randint(10, 100, (2, 3))

array([[59, 92, 11],
       [89, 59, 50]])

In [30]:
# listからランダムな値を取り出す。
a = [1, 2, 3]
np.random.choice(a)

3

## 統計量を求める
ndarrayの最小値、最大値、平均、中央値等を求める。

In [31]:
a = np.random.randn(3, 3)
a

array([[ 0.43293286, -0.30895856,  1.35683258],
       [ 0.43855434,  0.50148794,  0.03442318],
       [-0.80344425,  2.60059802,  1.83349636]])

In [41]:
# 最大値、最小値とそれぞれのインデックスを表示。※インデックスは.flattenしたときの番号
print('max:{} index:{}'.format(a.max(), a.argmax()))
print('min:{} index:{}'.format(a.min(), a.argmin()))

#argmaxのインデックスから行列の要素にアクセスしたいとき。
max_index = a.argmax()
i, j = max_index//a.shape[0], max_index%a.shape[0]
print(i, j)
print(a[i, j])

max:2.6005980241885824 index:7
min:-0.8034442531892279 index:6
2 1
2.6005980241885824


In [54]:
# 行ごと列ごとに最大値を求める。axis=0は列ごと、1は行ごと
print(a.max(axis=0))
print(a.max(axis=1))

[0.43855434 2.60059802 1.83349636]
[1.35683258 0.50148794 2.60059802]


In [42]:
#　平均
a.mean()

0.6762136076331775

In [44]:
# 中央値　→大きなデータだと算出に時間がかかる
np.median(a)

0.4385543383514287

In [52]:
# 中央値と平均値取得の時間差
import time
b = np.random.randn(1000, 1000)
before = time.time()
np.median(b)
after_median = time.time()
np.mean(b)
after_mean = time.time()

print('median: {} sec'.format(after_median - before))
print('mean: {} sec'.format(after_mean - after_median))

median: 0.015301942825317383 sec
mean: 0.0007874965667724609 sec


In [51]:
# 標準偏差
np.std(a) 

1.0123593987381212

## 数学関数

In [55]:
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [61]:
# numpyでのlogの底はデフォルトでネイピア数なので注意
# 公差1の数列を生成
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

## NaN(Not a Nunber)の扱い方
log(-2)したり、数学的に不正なことをするとnanが返ってくる。  
演算結果がnanかどうかを判定するのがnp.isnan。  
これらはpandasなどで様々な値を扱うときによく出てくる。

In [66]:
np.sqrt(-2)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [67]:
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [68]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## ndarrayのフィルタリング

In [70]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
# 3以下を3、9以上を9に置き換え。
# 漸近するような関数の値を扱うときに、小さすぎると負の無限大エラーが出るので、clipで下限を置き換えたりする。
np.clip(array, 3, 9)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9, 9])

In [79]:
# 配列の中で条件に合うものをTrue、そうでないものをFalseに置き換え
np.where(array > 5, True, False)

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [82]:
# 偶数を1、奇数を0に置き換え
np.where(array%2 == 0, 1, 0)

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [78]:
# 5以上のもののインデックスがタプルとして返され、それをアンパッキングしてaに格納。
a, = np.where(array > 5)
print(a)

[ 6  7  8  9 10 11 12 13 14]


In [87]:
print(array>5)

# よく使うフィルタリングの仕方。Trueのところだけ表示する
print(array[array>5])

[False False False False False False  True  True  True  True  True  True
  True  True  True]
[ 6  7  8  9 10 11 12 13 14]


In [88]:
ndarray = array.reshape(3, 5)
ndarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [90]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [93]:
# 行列の全要素が3より大きいか判定
(ndarray > 3).all() 

False

In [94]:
# 列単位で判定
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [95]:
# 行単位で判定
(ndarray > 3).all(axis=1)

array([False,  True,  True])

In [96]:
a = np.array([1, 1, 1, 2, 5, 29, 11, 11, 29, 2 ])
a

array([ 1,  1,  1,  2,  5, 29, 11, 11, 29,  2])

In [98]:
# 配列の重複を排除して表示。return_countsがTrueだとそれぞれの要素の出現回数を表示する
# 画像の各ピクセルに付けられたラベルが適切かどうかチェックするときなどに使う（0と1のラベルのみかどうかなど）
np.unique(a, return_counts=True)

(array([ 1,  2,  5, 11, 29]), array([3, 2, 1, 2, 2]))

In [99]:
# bincountは0から配列内のmaxまで連番で出現回数をカウントする
np.bincount(a)

array([0, 3, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2])

## 結合と転置

In [133]:
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [134]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [135]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [138]:
# stackは行列同士を結合するのではなく、重ねるイメージ。
# カラー画像を読み込むときはaxis=-1をよく使う。奥行きを-1に定義するため。
stacked_array = np.stack([ndarray_even, ndarray_odd], axis=-1)
stacked_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [139]:
stacked_array.shape

(3, 3, 2)

In [152]:
# axis=0の場合。(2, 3, 3)になる。
np.stack([ndarray_even, ndarray_odd], axis=0)

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [153]:
# axis=1の場合。(3, 2, 3)になる。
np.stack([ndarray_even, ndarray_odd], axis=1)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]]])

したがって、元の2つの配列(3, 3)に対して、axisに指定した軸（次元）の前にstackの引数に指定した配列の数（ここでは2）の要素が追加される。  
例）(3,3)の2つの配列をaxis=0でstack → (2, 3, 3)

In [156]:
np.stack([ndarray_even, ndarray_even,ndarray_even], axis=-1)

array([[[ 0,  0,  0],
        [ 2,  2,  2],
        [ 4,  4,  4]],

       [[ 6,  6,  6],
        [ 8,  8,  8],
        [10, 10, 10]],

       [[12, 12, 12],
        [14, 14, 14],
        [16, 16, 16]]])

In [149]:
# stackは一つのarrayに対しても使える
np.stack([ndarray_even], axis=0)

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]])

In [125]:
# 転置：transpose .T
# 画像データなどでaxisを変更するのに使う
a = np.random.randn(3, 2)
print(a)
print(a.shape)


[[-0.33223006  0.23366181]
 [ 0.32719056 -2.47379818]
 [ 0.58438517 -1.13018353]]
(3, 2)


In [127]:
transposed_a = a.T
transposed_a

array([[-0.33223006,  0.32719056,  0.58438517],
       [ 0.23366181, -2.47379818, -1.13018353]])

In [129]:
# 行・列が入れ替わる
transposed_a.shape

(2, 3)

In [124]:
np.transpose(a)

array([[-0.03274617,  0.50117791,  1.2769549 ],
       [-0.18064628, -1.05676707, -0.15544417]])

## NumPy Arrayをファイルとして保存する
ndarrayはファイルとして保存することができる。またその結果をロードすることも可能。  
また、ndarrayを含んだ辞書型もnp.saveで保存可能。

In [130]:
a = np.random.randn(2, 3, 4)
a.shape


(2, 3, 4)

In [131]:
a

array([[[-0.13324248,  0.62120338, -1.06068485, -2.00634766],
        [ 0.03084343, -0.27487832, -0.4863013 , -0.2389753 ],
        [-0.46591483,  1.1774956 ,  0.75255541, -0.52255017]],

       [[ 1.61536078,  1.08818111,  0.55874688,  1.73372034],
        [ 0.47272965,  2.48620498, -0.77671856,  0.82662324],
        [-0.91114817, -1.32431556,  1.17423202, -0.30252056]]])

In [135]:
# ファイル名をtest_arrayとしてカレントディレクトリに保存。拡張子省略可能。
np.save('./test_array', a)

In [138]:
# パスを指定してファイルから読み込み。拡張子省略不可。
loarded_a = np.load('./test_array.npy')
loarded_a

array([[[-0.13324248,  0.62120338, -1.06068485, -2.00634766],
        [ 0.03084343, -0.27487832, -0.4863013 , -0.2389753 ],
        [-0.46591483,  1.1774956 ,  0.75255541, -0.52255017]],

       [[ 1.61536078,  1.08818111,  0.55874688,  1.73372034],
        [ 0.47272965,  2.48620498, -0.77671856,  0.82662324],
        [-0.91114817, -1.32431556,  1.17423202, -0.30252056]]])

In [140]:
# データサイエンスでは辞書型に配列を格納するケースが多い。
d = {
    'id': 123456,
    'image': a
}

In [141]:
d

{'id': 123456,
 'image': array([[[-0.13324248,  0.62120338, -1.06068485, -2.00634766],
         [ 0.03084343, -0.27487832, -0.4863013 , -0.2389753 ],
         [-0.46591483,  1.1774956 ,  0.75255541, -0.52255017]],
 
        [[ 1.61536078,  1.08818111,  0.55874688,  1.73372034],
         [ 0.47272965,  2.48620498, -0.77671856,  0.82662324],
         [-0.91114817, -1.32431556,  1.17423202, -0.30252056]]])}

In [143]:
# 辞書型もnp.saveで保存可能
np.save('test_dic', d)

In [150]:
# alloe_pickle=Trueでないとエラーが起きる。pickleとはPythonにおけるデータ保存形式
loaded_d = np.load('test_dic.npy', allow_pickle=True)
loaded_d

array({'id': 123456, 'image': array([[[-0.13324248,  0.62120338, -1.06068485, -2.00634766],
        [ 0.03084343, -0.27487832, -0.4863013 , -0.2389753 ],
        [-0.46591483,  1.1774956 ,  0.75255541, -0.52255017]],

       [[ 1.61536078,  1.08818111,  0.55874688,  1.73372034],
        [ 0.47272965,  2.48620498, -0.77671856,  0.82662324],
        [-0.91114817, -1.32431556,  1.17423202, -0.30252056]]])},
      dtype=object)

In [151]:
# loadしたデータから辞書だけ取り出す書き方
loaded_d[()]

{'id': 123456,
 'image': array([[[-0.13324248,  0.62120338, -1.06068485, -2.00634766],
         [ 0.03084343, -0.27487832, -0.4863013 , -0.2389753 ],
         [-0.46591483,  1.1774956 ,  0.75255541, -0.52255017]],
 
        [[ 1.61536078,  1.08818111,  0.55874688,  1.73372034],
         [ 0.47272965,  2.48620498, -0.77671856,  0.82662324],
         [-0.91114817, -1.32431556,  1.17423202, -0.30252056]]])}

## 多次元配列のイメージ
n次元の配列は、n-1次元の配列が並んでいるものと考えるとイメージしやすい。  
例えば、.shapeが(2, 3, 4)の3次元行列は2次元行列(3, 4)が2つ並んだもの。  
(2, 3, 4, 5)の4次元配列は3次元配列(3, 4, 5)が2つ並んだもの。  
参考：https://ylb.jp/2005a/proa/multidimension.pdf

## Numpy arrayのテクニック

### Trueの箇所にのみ値を入れる

In [67]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
filter_array = np.array([[True, False, True], [True, False, False],[True, False, True]])
filter_array

array([[ True, False,  True],
       [ True, False, False],
       [ True, False,  True]])

In [70]:
# Trueの要素だけ1次元配列で表示される。
zeros[filter_array]

array([0., 0., 0., 0., 0.])

In [71]:
# Trueの個所にのみ1を代入 
zeros[filter_array] = 1

In [72]:
zeros

array([[1., 0., 1.],
       [1., 0., 0.],
       [1., 0., 1.]])

In [75]:
# リストで値をいれることも可能。
zeros[filter_array] = [2, 5, 3, 4, 5]

In [76]:
zeros

array([[2., 0., 5.],
       [3., 0., 0.],
       [4., 0., 5.]])

### 配列を低次の配列でフィルタリングする
例えばshapeが(3, 3, 4)の配列を低次の配列(3, 3)のTrue要素でフィルタリングすると、  
[ Trueの行インデックス, Trueの列インデックス, : ]のようにフィルタリングしたことになる。

In [90]:
# 3行4列の配列が3つの3次元配列
zeros = np.zeros((3, 3, 4))
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [91]:
zeros.shape

(3, 3, 4)

In [92]:
# 3行3列のフィルター用2次元配列
filter_array = np.array([[True, False, True], [True, False, False],[True, False, True]])
filter_array

array([[ True, False,  True],
       [ True, False, False],
       [ True, False,  True]])

In [93]:
filter_array.shape

(3, 3)

In [94]:
# フィルタリング
zeros[filter_array]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

この場合、3次元配列(3, 3, 4)は2次元配列(3, 3)でフィルタリングすると、3次元配列の次元のうち前二つ(3, 3)まで  
指定していることになる。例えば、filter_arrayでは[0, 2]の要素がTrueになっているので、zeros[0, 2, :]のように  
フィルタリングしていることに相当する。最後の次元のインデックス（列を指定するインデックス）は指定されていないため、行まるごと（リスト）が返ってくる。

In [98]:
# フィルタリングした結果の要素全てに1を入れる。
zeros[filter_array]= 1
zeros[filter_array]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
zeros

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.]]])

In [101]:
zeros[filter_array]= 0
zeros[filter_array]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
# 要素数が同じリストを指定すると、行ごとに代入される。
zeros[filter_array] = [255, 1 ,2, 3]
zeros[filter_array]

array([[255.,   1.,   2.,   3.],
       [255.,   1.,   2.,   3.],
       [255.,   1.,   2.,   3.],
       [255.,   1.,   2.,   3.],
       [255.,   1.,   2.,   3.]])

In [106]:
zeros

array([[[255.,   1.,   2.,   3.],
        [  0.,   0.,   0.,   0.],
        [255.,   1.,   2.,   3.]],

       [[255.,   1.,   2.,   3.],
        [  0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.]],

       [[255.,   1.,   2.,   3.],
        [  0.,   0.,   0.,   0.],
        [255.,   1.,   2.,   3.]]])