# 深層学習ノートブック-1 Tensor（テンサー、テンソル）の取り扱い基礎
Tensorはテンサーが正式な読み方ぽい。  
テンサーは学部の頃に勉強した気がしたが忘れたので、ひとまずは多次元配列のことと理解しておく。  
PytorchにおけるTensorも多次元配列のようなイメージであり、以下の特徴を持つ。  
* 深層学習の計算の核となるデータ構造
* Numpy Arrayと非常によく似ている
* GPUによる計算の高速化が可能
* 自動微分(Auto Grad)が可能

参考:  
https://remedics.air-nifty.com/academy/2020/02/post-fbe026.html

In [31]:
# import torchでpytorchをimport
import torch
import numpy as np

# torchで使う疑似乱数のseedは設定
torch.manual_seed(42)

## ・Tensorの作成
torch.tensor()にlistを入れることでtensorを作成出来る。
デフォルトの要素のデータ型はfloat32である。  
深層学習では扱うデータ量が多いので、データ型を意識してなるべく省メモリで作ることが重要。  
torch.tensor()のdtype引数を使ってデータ型を指定可能。（例:dtype=torch.float64）

In [8]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [9]:
type(tensor_from_list)

torch.Tensor

In [10]:
# intを入れて作成すると、データ型はtorch.int64になる
tensor_from_list.dtype

torch.int64

In [5]:
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [6]:
tensor_from_list.dtype

torch.float32

In [12]:
# dtypeを指定することで別の型で作成可能
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

## ・Tensor生成関数
numpyのように基本的な配列を生成できる関数がある。

In [17]:
# 2 x 3で要素が全て０のテンサー作成
zeros_tensor = torch.zeros((2, 3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
# 2 x 3で要素が全て1のテンサー作成
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [24]:
# 4 x 4で単位行列作成
ones_tensor = torch.eye(4)
ones_tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [26]:
# 4 x 2で要素がランダムのテンサー作成
rand_tensor = torch.rand(4, 2)
rand_tensor

tensor([[0.0203, 0.6887],
        [0.8151, 0.4862],
        [0.9432, 0.0836],
        [0.6376, 0.9593]])

## ・Tensorのshapeを確認

In [30]:
zeros_tensor.shape

torch.Size([4, 4])