# 深層学習ノートブック-1 Tensorの取り扱い基礎
Tensorはテンサーが正式な読み方ぽい。  
テンサーは学部の頃に勉強したが忘れたので、ひとまずは多次元配列のことと理解しておく。  
PytorchにおけるTensorも多次元配列のようなイメージであり、以下の特徴を持つ。  
* 深層学習の計算の核となるデータ構造
* Numpy Arrayと非常によく似ている
* GPUによる計算の高速化が可能
* 自動微分(Auto Grad)が可能

参考:  
https://remedics.air-nifty.com/academy/2020/02/post-fbe026.html  
https://manabitimes.jp/math/1845  

In [2]:
# import torchでpytorchをimport
import torch
import numpy as np

# torchで使う疑似乱数のseedは設定
torch.manual_seed(42)

## ・Tensorの作成
torch.tensor()にlistを入れることでtensorを作成出来る。  
デフォルトの要素のデータ型はfloat32である。（numpyはfloat64がデフォルトなので注意）  
深層学習では扱うデータ量が多いので、データ型を意識してなるべく省メモリで作ることが重要。  
torch.tensor()のdtype引数を使ってデータ型を指定可能。（例:dtype=torch.float64）

In [11]:
my_list = [1, 2, 3, 4]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1, 2, 3, 4])

In [12]:
type(tensor_from_list)

torch.Tensor

In [13]:
# intを入れて作成すると、データ型はtorch.int64になる
tensor_from_list.dtype

torch.int64

In [14]:
my_list = [1., 2., 3., 4.]
tensor_from_list = torch.tensor(my_list)
tensor_from_list

tensor([1., 2., 3., 4.])

In [15]:
tensor_from_list.dtype

torch.float32

In [16]:
# dtypeを指定することで別の型で作成可能
tensor_from_list = torch.tensor(my_list, dtype=torch.float64)
tensor_from_list

tensor([1., 2., 3., 4.], dtype=torch.float64)

In [18]:
# tensorのshapeを表示
tensor_from_list.shape

torch.Size([4])

## ・Tensor生成関数
numpyのように基本的な配列を生成できる関数がある。

In [7]:
# 2 x 3で要素が全て０のテンサー作成
zeros_tensor = torch.zeros((2, 3))
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# 2 x 3で要素が全て1のテンサー作成
ones_tensor = torch.ones((2, 3))
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# 4 x 4で単位行列作成
ones_tensor = torch.eye(4)
ones_tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [20]:
# 4 x 2で要素がランダムのテンサー作成
rand_tensor = torch.rand(4, 2)
rand_tensor

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936]])

## ・Tensorのshapeを確認

In [21]:
zeros_tensor.shape

torch.Size([2, 3])

## ・Tensorの操作

In [30]:
# 2x3x4の3次元配列を作成。torchはタプルでそのまま入れることに注意
tensor_example = torch.rand((2, 3, 4))
np_example = np.random.rand(2, 3, 4)

In [31]:
tensor_example

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

In [32]:
tensor_example.shape

torch.Size([2, 3, 4])

※復習：  
多次元配列のshapeの各インデックスをRankと呼ぶのであった。  
上記ではRank=0は2、Rank=1は3、Rank=2は4。N次元配列のshapeは左からイメージしていくとわかりやすい。  
上記の3次元配列の場合は、奥行き2、縦3、横4という形状の配列である。  

### - permute
Rankを入れ替える操作。

In [33]:
# 転置。引数の配列のRankをどう並び替えるか指定する。
permuted_tensor = torch.permute(tensor_example, (1, 0, 2) )
permuted_tensor

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.5472, 0.0062, 0.9516, 0.0753],
         [0.6343, 0.3644, 0.7104, 0.9464]],

        [[0.8860, 0.5832, 0.3376, 0.8090],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

In [34]:
permuted_tensor.shape

torch.Size([3, 2, 4])

元のtensorからshapeが入れ替わっている。

In [35]:
# numpyの場合、上記のtransposeに相当する。
# 一方、pytorchのtransposeは2軸を入れ変える操作なので混同しないように注意。
# 使い方としては対象のtensor, 入れ替え対象のRankその1, 入れ替え対象のRankその2という感じ。
torch.transpose(tensor_example, 0, 1)

tensor([[[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.5472, 0.0062, 0.9516, 0.0753],
         [0.6343, 0.3644, 0.7104, 0.9464]],

        [[0.8860, 0.5832, 0.3376, 0.8090],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

上記の場合、Rank=0とRank=1を入れ替える操作となる。  
入れ替えではなく最大のRank数もいじる場合はreshapeを用いる。

### - reshape

In [36]:
# reshape.3 x 2 x 4だったtensorを6 x 4にreshapeする
reshaped_tensor = torch.reshape(tensor_example, (6, 4) )
print(reshaped_tensor)

tensor([[0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])


In [40]:
reshaped_tensor[0] = 0
reshaped_tensor

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.5472, 0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464],
        [0.7890, 0.2814, 0.7886, 0.5895]])

In [41]:
tensor_example

tensor([[[0.0000, 0.0000, 0.0000, 0.0000],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]],

        [[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]]])

### ！注意
torch.reshapeの結果はreshape前のtensor_exapmleと同じメモリを参照しているため、  
reshaped_tensorに何か操作を施すと、元のtensor_exampleも変更されてしまうことに注意。  
これはtorch側でメモリを節約するための工夫である。  
ただし、tensor_exampleがメモリ上に連続的に格納されていない場合は、参照ではなくコピーを返す。

In [44]:
# 例
x = torch.tensor([[1, 2], [3, 4], [5, 6]])
# rank2なら.Tで転置可能
y = x.T

In [45]:
# メモリに連続的に保存されているか確認する
y.is_contiguous()

False

In [47]:
y.shape

torch.Size([2, 3])

In [48]:
# tensor.reshape()という書き方もできる
z = y.reshape((1, 6))

In [50]:
z[0] = 0
z

tensor([[0, 0, 0, 0, 0, 0]])

In [51]:
# reshape元は変更されていない。
y

tensor([[1, 3, 5],
        [2, 4, 6]])

上記のようにreshape元がメモリに連続的に保存されてい無ければ、  
reshape結果はコピーとなる。  
メモリ節約のために参照かコピーかを厳密に気にしながらreshapeする必要がある場合は.viewを使用するとよい。  
.viewはメモリに連続的に保存されている場合のみ（参照可能な場合のみ）shapeが変更される。不連続の場合はエラーとなる。  

In [55]:
# yは不連続なメモリに保存されているのでエラーになる
y.view((1, 6))

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [57]:
# xは連続的なので変形可能
print(x.is_contiguous())
x.view((1, 6))

True


tensor([[1, 2, 3, 4, 5, 6]])

### - flatten
tensorを１次元（Rank0）にする操作。

In [60]:
# reshape.3 x 2 x 4だったtensorを6 x 4にreshapeする
flattend_tensor = torch.flatten(tensor_example)
print(flattend_tensor)
print(flattend_tensor.shape)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860,
        0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644,
        0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895])
torch.Size([24])


In [62]:
# 元々の形状
print(tensor_example.shape)

torch.Size([2, 3, 4])


### - flatten
tensorを１次元（Rank0）にする操作。

In [63]:
flattend_tensor = torch.flatten(tensor_example)
print(flattend_tensor)
print(flattend_tensor.shape)

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860,
        0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644,
        0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895])
torch.Size([24])


### - squeeze
余分な次元を削除する操作。

In [65]:
tensor_example = torch.tensor([[[1], [2], [3]]])
print(tensor_example.shape)

torch.Size([1, 3, 1])


上記のRank=0,2はあってもなくてもよく、Rank=1の1列だけあれば情報としては事足りる場合がある。

In [66]:
squeezed_tensor =torch.squeeze(tensor_example)
print(squeezed_tensor)
print(squeezed_tensor.shape)

tensor([1, 2, 3])
torch.Size([3])


上記の通り無くてもかまわないRank=0とRank=2が削除されてすっきりさせることが出来る。

### - unsqueeze
Rankを増やす操作

In [68]:
# Rank=0の前に新たなRankを追加する。
unsqueezed_tensor =torch.unsqueeze(tensor_example, 0)
print(unsqueezed_tensor)
print(unsqueezed_tensor.shape)

tensor([[[[1],
          [2],
          [3]]]])
torch.Size([1, 1, 3, 1])


上記のように任意の場所にRankを追加できる。

In [70]:
# 下記のようなの書き方でも追加可能。
tensor_example[None, :, :, :].shape

torch.Size([1, 1, 3, 1])

## ・Tensorの便利関数
numpyと同様にsum,mean等がある。

In [73]:
tensor_example = torch.rand((2, 3))
print(tensor_example)

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])


In [76]:
# 合計。どちらの書き方でもOK
print(torch.sum(tensor_example))
print(tensor_example.sum())

tensor(2.7212)
tensor(2.7212)


In [81]:
torch.sqrt(tensor_example)

tensor([[0.7290, 0.3984, 0.8088],
        [0.5725, 0.8082, 0.6291]])

戻り値はfloatではなく全てtensorであることに注意。  
数字だけ取り出したいときは.item()を使う。

In [78]:
torch.sum(tensor_example).item()

2.72123384475708

## ・Tensorの演算
numpy arrayと同様にTensorでも配列の要素ごとの四則演算、行列の積（内積）が計算できる。  

■ 加減算および要素毎の乗除算  
* Numpy Arrayと同様 (+, -, *, /)  

■ 行列の積(内積)  →深層学習ではよく使う  
* torch.mm()/torch.matmul() もしくは@演算子を使用  
    ※mmやmatmulはMatrix Multiplyの略  
* Numpy Arrayではnp.dot()または@演算子を使用  
* torch.dot()は，1次元に対してのみドット積(ベクトルの内積)を計算  

### - 要素ごとの四則演算

In [4]:
a = torch.rand((3, 3))
b = torch.rand((3, 3))
print(a)
print(b)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [7]:
# 加法
a + b

tensor([[0.4659, 1.1746, 0.2758],
        [1.3929, 0.3722, 1.7177],
        [0.6885, 0.6071, 1.1678]])

In [9]:
# 減法
a - b

tensor([[ 0.0672,  0.0803,  0.2635],
        [-0.5102,  0.2217, -0.0543],
        [-0.4779, -0.0682, -0.4502]])

In [10]:
# 乗法
a * b

tensor([[0.0531, 0.3433, 0.0017],
        [0.4200, 0.0223, 0.7369],
        [0.0614, 0.0910, 0.2903]])

In [11]:
# 除法
a / b

tensor([[ 1.3372,  1.1467, 43.7683],
        [ 0.4638,  3.9450,  0.9387],
        [ 0.1806,  0.7982,  0.4435]])

### - Tensorの積
tensorの積の計算は以下３通りある。@の書き方がよく用いられる。  

In [13]:
# a・bと同じ意味。順番注意。
torch.mm(a, b)

tensor([[0.8075, 0.2841, 0.7757],
        [0.8556, 0.5447, 0.9386],
        [0.4867, 0.1991, 0.5297]])

In [14]:
torch.matmul(a, b)

tensor([[0.8075, 0.2841, 0.7757],
        [0.8556, 0.5447, 0.9386],
        [0.4867, 0.1991, 0.5297]])

In [17]:
# よく使う書き方
a @ b

tensor([[0.8075, 0.2841, 0.7757],
        [0.8556, 0.5447, 0.9386],
        [0.4867, 0.1991, 0.5297]])

### - ブロードキャスティング
* Numpy同様，broad castingの機能がある  
* 復習：演算する2つのtensorが同じ次元ではない場合，次元が少ない方が次元を増やすことで演算を可能にする仕組み  
* 深層学習では頻出  
* ブロードキャスティングのルール  
    * rank数が異なる場合，少ない方の配列のshapeの左側にサイズ1の次元を追加する(例: (2, 3) -> (1, 2, 3))  
    * shapeの右側から値(サイズ数)を比較し、数が一致するか、サイズが1であればブロードキャスティングが可能  
    * サイズ1の次元を大きい方の次元のサイズへ拡大する。この際、値はコピーされる。

### 例1)

In [57]:
temp1 = torch.rand((3, 2)) * 100
temp2 = torch.rand((2)) * 100
print(f'shape of temp1 :{temp1.shape}')
print(temp1)
print('-------------')
print(f'shape of temp2 :{temp2.shape}')
print(temp2)

shape of temp1 :torch.Size([3, 2])
tensor([[33.3572, 57.8186],
        [ 6.0039, 28.4563],
        [20.0666, 50.1386]])
-------------
shape of temp2 :torch.Size([2])
tensor([31.3948, 46.5352])


In [58]:
temp1 + temp2

tensor([[ 64.7520, 104.3538],
        [ 37.3988,  74.9916],
        [ 51.4614,  96.6738]])

temp2がブロードキャスティングされてtemp1に足されていることが分かる。

### 例2) (3,3)とスカラーの演算

In [60]:
a = torch.rand(3, 3)
scalar = 5
a + scalar

tensor([[5.0766, 5.8460, 5.3624],
        [5.3083, 5.0850, 5.0029],
        [5.6431, 5.3908, 5.6947]])

### 例3) (3, 3)と(1, 3)の演算

In [62]:
b = torch.rand(1, 3)
b

tensor([[0.0897, 0.8712, 0.1330]])

In [63]:
a + b

tensor([[0.1663, 1.7172, 0.4954],
        [0.3980, 0.9562, 0.1359],
        [0.7327, 1.2620, 0.8276]])

In [64]:
a

tensor([[0.0766, 0.8460, 0.3624],
        [0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947]])

### 例4) (32, 128, 128, 3)と(128, 128, 3)の演算

In [73]:
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 3))

In [74]:
a + b

tensor([[[[0.7710, 1.4229, 0.5530],
          [1.0756, 0.8071, 1.6654],
          [0.9835, 0.9913, 1.8300],
          ...,
          [0.6746, 1.1276, 1.1759],
          [1.6491, 0.8438, 1.0421],
          [1.0628, 1.0259, 0.5029]],

         [[0.2446, 1.7456, 1.0428],
          [1.2247, 0.6800, 1.6920],
          [1.6483, 1.0392, 1.1523],
          ...,
          [1.3965, 1.1794, 0.9092],
          [0.9807, 1.5331, 0.8732],
          [0.7846, 1.0218, 0.9091]],

         [[0.6367, 0.8302, 0.6155],
          [1.2663, 1.3417, 0.6631],
          [1.0617, 0.5932, 1.0978],
          ...,
          [1.0029, 1.3304, 1.4227],
          [0.8284, 1.6720, 1.0244],
          [1.4785, 0.6243, 1.0308]],

         ...,

         [[0.4339, 0.5114, 1.2578],
          [1.1774, 1.1114, 0.3516],
          [1.3588, 1.2006, 0.5233],
          ...,
          [1.0652, 0.2965, 0.7732],
          [1.1293, 0.9161, 1.0054],
          [1.3012, 1.3583, 1.0479]],

         [[0.2182, 1.5599, 0.9472],
          [1.1068

結果：計算可能

### 例5) (32, 128, 128, 3)と(128, 128, 6)の演算

In [75]:
a = torch.rand((32, 128, 128, 3))
b = torch.rand((128, 128, 6))

In [76]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 3

一番右のRankが両者で異なるので、ブロードキャスティングできない。

### 例6) (1, 128, 128, 3)と(8, 128, 128, 1)の演算  
rank0では前者が、rank3では後者の次元が低いtensorの場合。

In [80]:
a = torch.rand((1, 128, 128, 3))
b = torch.rand((8, 128, 128, 1))

In [81]:
a + b

tensor([[[[0.5604, 0.3802, 0.9534],
          [0.7845, 1.2659, 0.9637],
          [1.1564, 1.5344, 1.0868],
          ...,
          [1.0127, 0.9974, 1.5632],
          [1.3757, 0.9418, 1.5401],
          [1.3365, 0.6936, 0.8698]],

         [[0.1989, 0.9930, 0.6176],
          [1.0474, 1.0387, 0.9743],
          [0.4889, 0.7482, 0.3083],
          ...,
          [0.7021, 1.0262, 1.0312],
          [0.9161, 0.9434, 0.7452],
          [1.0048, 1.4666, 1.1286]],

         [[1.4104, 1.4833, 1.6604],
          [0.6810, 0.9959, 0.4219],
          [1.1556, 1.3073, 1.0011],
          ...,
          [0.7069, 1.1351, 0.2913],
          [1.5982, 1.1518, 1.2421],
          [0.9593, 1.1763, 1.6168]],

         ...,

         [[1.2587, 0.8883, 1.3228],
          [0.8341, 1.1248, 1.1193],
          [0.5390, 0.8507, 0.2386],
          ...,
          [1.0532, 0.8762, 0.9433],
          [0.6722, 0.8187, 1.0094],
          [1.7713, 1.2609, 1.6200]],

         [[0.8755, 0.3195, 0.7582],
          [1.5264

In [82]:
(a+b).shape

torch.Size([8, 128, 128, 3])

aとbの両方ブロードキャスティングされるので、これは演算可能。  